### ISSUE TITLE
question: How I can disable the cursor on the next line?

### ISSUE THREAD

**Issue by zer09** [thousandtyone/autoend#4]
Is there way to disable that when you ```;``` it will not go to the next line? it will just jump to the end of the line.

thanks

**Comment by thousandtyone** [comment]
@zer09 - This is included in the home page (if you scroll down to the documentation section). https://github.com/thousandtyone/autoend/ - here is the part from the documentation that explains how you can do this:

Note: Use autoend.autoInsertNewline in VS Code settings to control if autoend automically inserts a new line and moves you to the new line. Default behavior is to automtically move to new line. To prevent automatic move to new line change this setting to false. Visual Studio Code restart is required after setting change.

You can take a quick look at this: https://code.visualstudio.com/docs/getstarted/settings if you are not sure how to change VS Code settings.

Please feel free to close this issue if this answers your question.

**Comment by thousandtyone** [comment]
Closing this since we did not hear back from you. Please feel free to re-open if the previous comment we posted does not solve the issue for you.
